version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  backend:
    depends_on:
      - mysqldb
    build: ./Backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 3500:3500
    environment:
      - DB_HOST=mysqldb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=3306
      - CLIENT_ORIGIN=http://127.0.0.1:3500
    networks:
      - backend
      - frontend
  frontend:
    depends_on:
      - backend
    build:
      context: ./Frontend
      args:
        - REACT_APP_API_BASE_URL=http://127.0.0.1:3000
    ports:
      - 3000:3000
    networks:
      - frontend

volumes:
  db:
networks:
  backend:
  frontend: