version: "3.4"

services:

  mysql-db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_container
    env_file: ./Backend/.env
    environment:
      - MYSQL_ROOT_PASSWORD=jobapp
      - MYSQL_DATABASE=express-boilerplat
    ports:
      - 9906:3306
    restart: unless-stopped
    volumes:
      - ./db/database.sql:/docker-entrypoint-intidb.d/database.sql

  server:
    build:
      context: ./Backend
    container_name: node_server_container
    env_file: ./Backend/.env
    depends_on:
      - mysql-db
    ports:
      - 3500:3500
    volumes:
      - ./Backend:/app
    links:
      - mysql-db
    command: npm start

  client:
    build:
      context: ./Frontend
    container_name: client_container
    depends_on:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./Frontend/src:/app/src
    links:
      - server
    command: npm start
